name: Python CI/CD

# on: [push, pull_request]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run tests
#       run: |
#         # Add your test command here
#         # For example, if you're using pytest:
#         pytest
#     - name: Deploy
#       run: |
#         # Add your deployment commands here
#         # This will depend on your hosting provider